//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneApp1.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collapse fullscreen.
        /// </summary>
        internal static string CollapseFullScreenButton {
            get {
                return ResourceManager.GetString("CollapseFullScreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when trying to mark the book as interesting..
        /// </summary>
        internal static string CouldNotLikeBook {
            get {
                return ResourceManager.GetString("CouldNotLikeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CouldNotLikeHighlight {
            get {
                return ResourceManager.GetString("CouldNotLikeHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullscreen.
        /// </summary>
        internal static string FullScreenButton {
            get {
                return ResourceManager.GetString("FullScreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highlights.
        /// </summary>
        internal static string HighlightsButton {
            get {
                return ResourceManager.GetString("HighlightsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like book.
        /// </summary>
        internal static string LikeBookButton {
            get {
                return ResourceManager.GetString("LikeBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        internal static string LikeHighlightButton {
            get {
                return ResourceManager.GetString("LikeHighlightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no books in your collection yet.
        /// </summary>
        internal static string NoCollectedBooksMsg {
            get {
                return ResourceManager.GetString("NoCollectedBooksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, no one seems to have highlighted this book yet..
        /// </summary>
        internal static string NoHighlights {
            get {
                return ResourceManager.GetString("NoHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no description or story available for this book yet..
        /// </summary>
        internal static string NoStoryMsg {
            get {
                return ResourceManager.GetString("NoStoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to internet. App functionality is limited in the offline mode. For full access please connect to the network and restart the application..
        /// </summary>
        internal static string NotConnectedMsg {
            get {
                return ResourceManager.GetString("NotConnectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Network.
        /// </summary>
        internal static string NotConnectedMsgTitle {
            get {
                return ResourceManager.GetString("NotConnectedMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search title or author.
        /// </summary>
        internal static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike book.
        /// </summary>
        internal static string UnlikeBookButton {
            get {
                return ResourceManager.GetString("UnlikeBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike.
        /// </summary>
        internal static string UnlikeHighlightButton {
            get {
                return ResourceManager.GetString("UnlikeHighlightButton", resourceCulture);
            }
        }
    }
}
