//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneApp1.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you are logged-out or authorization for Read Rover has expired. You&apos;ll need to authorize the rover to access your Readmill account again..
        /// </summary>
        internal static string AuthFailed {
            get {
                return ResourceManager.GetString("AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Failed.
        /// </summary>
        internal static string AuthFailedTitle {
            get {
                return ResourceManager.GetString("AuthFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books collection is null.
        /// </summary>
        internal static string BooksCollectionNull {
            get {
                return ResourceManager.GetString("BooksCollectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collapse.
        /// </summary>
        internal static string CollapseFullScreenButton {
            get {
                return ResourceManager.GetString("CollapseFullScreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when trying to mark the book as &apos;interesting&apos; on Readmill and adding it to your collection..
        /// </summary>
        internal static string CouldNotLikeBook {
            get {
                return ResourceManager.GetString("CouldNotLikeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CouldNotLikeHighlight {
            get {
                return ResourceManager.GetString("CouldNotLikeHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullscreen.
        /// </summary>
        internal static string FullScreenButton {
            get {
                return ResourceManager.GetString("FullScreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        internal static string GenericLoadingMsg {
            get {
                return ResourceManager.GetString("GenericLoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highlights.
        /// </summary>
        internal static string HighlightsButton {
            get {
                return ResourceManager.GetString("HighlightsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights collection is null.
        /// </summary>
        internal static string HighlightsCollectionNull {
            get {
                return ResourceManager.GetString("HighlightsCollectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like book.
        /// </summary>
        internal static string LikeBookButton {
            get {
                return ResourceManager.GetString("LikeBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Like.
        /// </summary>
        internal static string LikeFailedTitle {
            get {
                return ResourceManager.GetString("LikeFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        internal static string LikeHighlightButton {
            get {
                return ResourceManager.GetString("LikeHighlightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to &apos;like&apos; this highlight..
        /// </summary>
        internal static string LikeReadmillHighlightFailed {
            get {
                return ResourceManager.GetString("LikeReadmillHighlightFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must authorize Read Rover to access your Readmill account to continue using the app..
        /// </summary>
        internal static string MustAuthorize {
            get {
                return ResourceManager.GetString("MustAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Authorize.
        /// </summary>
        internal static string MustAuthorizeTitle {
            get {
                return ResourceManager.GetString("MustAuthorizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no books in your collection yet..
        /// </summary>
        internal static string NoCollectedBooksMsg {
            get {
                return ResourceManager.GetString("NoCollectedBooksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not saved any highlights on this device yet. Start collecting now!.
        /// </summary>
        internal static string NoCollectedHighlights {
            get {
                return ResourceManager.GetString("NoCollectedHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, no one seems to have highlighted this book yet..
        /// </summary>
        internal static string NoHighlights {
            get {
                return ResourceManager.GetString("NoHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reading for this book for current user..
        /// </summary>
        internal static string NoReadingEx {
            get {
                return ResourceManager.GetString("NoReadingEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no description or story available for this book yet..
        /// </summary>
        internal static string NoStoryMsg {
            get {
                return ResourceManager.GetString("NoStoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to internet. A network connection is needed for Read Rover to function. Please connect and restart the application..
        /// </summary>
        internal static string NotConnectedMsg {
            get {
                return ResourceManager.GetString("NotConnectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Network.
        /// </summary>
        internal static string NotConnectedMsgTitle {
            get {
                return ResourceManager.GetString("NotConnectedMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just read.
        /// </summary>
        internal static string RecentlyReadPageTitle {
            get {
                return ResourceManager.GetString("RecentlyReadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search title or author.
        /// </summary>
        internal static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading books and highlights seems to be taking long. Your internet connection maybe slow. Press &apos;ok&apos; if you want the rover to continue trying to load. Press &apos;cancel&apos; or back key to stop loading..
        /// </summary>
        internal static string TimeoutMsg {
            get {
                return ResourceManager.GetString("TimeoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Things Are Slow!.
        /// </summary>
        internal static string TimeoutMsgTitle {
            get {
                return ResourceManager.GetString("TimeoutMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something bad happened and the rover doesn&apos;t know how to handle this situation. It&apos;s best to exit and start again. Sorry!.
        /// </summary>
        internal static string UnknownFatalError {
            get {
                return ResourceManager.GetString("UnknownFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UnknownFatalErrorTitle {
            get {
                return ResourceManager.GetString("UnknownFatalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to connect to Readmill. The rover isn&apos;t sure but it might be a connectivity issue. Please check your network connection and try again..
        /// </summary>
        internal static string UnknownWebError {
            get {
                return ResourceManager.GetString("UnknownWebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        internal static string UnknownWebErrorTitle {
            get {
                return ResourceManager.GetString("UnknownWebErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike book.
        /// </summary>
        internal static string UnlikeBookButton {
            get {
                return ResourceManager.GetString("UnlikeBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Unlike.
        /// </summary>
        internal static string UnlikeFailedTitle {
            get {
                return ResourceManager.GetString("UnlikeFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike.
        /// </summary>
        internal static string UnlikeHighlightButton {
            get {
                return ResourceManager.GetString("UnlikeHighlightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to something went wrong while trying to &apos;unlike&apos; this highlight..
        /// </summary>
        internal static string UnlikeReadmillHighlightFailed {
            get {
                return ResourceManager.GetString("UnlikeReadmillHighlightFailed", resourceCulture);
            }
        }
    }
}
